### ISSUE TITLE
The connexion is not persistant 

### ISSUE THREAD

**Issue by JnTournier** [ahhh/Reverse_HTTPS_Bot#1]
Hi, 
I test your tool, but i run the server, and the bot on the client, 
but i can not change the command i would run on the client. 

Moreover When i run the bot, i do not have the message which shows that the 
client is connected to the server. So the connection between them is not the same 
and the initial command is sent each time.

**Comment by ahhh** [comment]
I'm afraid I don't follow @jonathanTournier. 

While the bot def needs some work you can change the command that is run by hitting the following endpoint or by simply editing the text file ("command") it creates:
https://github.com/ahhh/Reverse_HTTPS_Bot/blob/master/server.js#L98
Although the bot itself only accepts a limited set of commands, you can use those in endless ways (just running raw linux commands through the bot).

Also, the server raises a message when the client connects back, but the client dosn't raise any messages because the idea is you want the client to be silent: https://github.com/ahhh/Reverse_HTTPS_Bot/blob/master/server.js#L34
Although it could be cool to log this to a text file.

Finally, I'm not sure I follow the "connection between them is not the same" part, the connection will keep calling back so long as the bot is running but the bot does not use any persistence mechanisms on the machine to continue running later.

**Comment by JnTournier** [comment]
You have no reason to be afraid, I am a good boy, interested by computer security =)

Well, finally I found my errors -> When I chose my ADMIN_HOST, i put the server IPv4 adresse,
but when the function CheckIP compared the adresses (ADMIN_HOST and HOST who is connected), the result was false. Indeed the IP of the HOST is the combinaison of his IPv4 and IPv6, and by default the "res.write(Unauthorized)" is commented ... so I did not receive the error, and my command was not sent.
It's not a huge error and i am sorry for the inconvenience

And the tool is very nice =)
